spring:
  application:
    name: secure-media-vault-api

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/media_vault
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  main:
    web-application-type: reactive

server:
  port: 8081

minio:
  url: http://localhost:9200
  accessKey: minio
  secretKey: minio123
